# Generated by Django 5.2.5 on 2025-09-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('comida', 'Comida'), ('sobremesa', 'Sobremesa'), ('drinks', 'Drinks')], default='comida', max_length=50, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='receitas/images/', verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='ingredients',
            field=models.TextField(verbose_name='Ingredientes'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='instructions',
            field=models.TextField(verbose_name='Instruções'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
    ]
